// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package db

import (
	"time"

	"github.com/google/uuid"
)

type TbChat struct {
	ID           uuid.UUID
	Participants []uuid.UUID
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type TbMessage struct {
	ID        uuid.UUID
	ChatID    uuid.UUID
	UserID    uuid.UUID
	Message   string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type TbUser struct {
	ID        uuid.UUID
	Email     string
	Password  string
	Username  string
	CreatedAt time.Time
	UpdatedAt time.Time
}
